export { default as porsche } from "./porsche.webp";
export { default as telsa } from "./tesla.png";
export { default as lambo } from "./lambo.png";
export { default as bugatti } from "./bugatti.png";

export { default as logoPorche } from "./logos/porsche.png";
export { default as logoAudi } from "./logos/audi.png";
export { default as logoBmw } from "./logos/bmw.png";
export { default as logoBugatti } from "./logos/bugatti.png";
export { default as logoCadillac } from "./logos/cadillac.png";
export { default as logoFerrari } from "./logos/ferrari.png";
export { default as logoJaguar } from "./logos/jaguar.png";
export { default as logoLambo } from "./logos/lambo.png";
export { default as logoLexus } from "./logos/lexus.png";
export { default as logoMaserati } from "./logos/maserati.png";
export { default as logoBenz } from "./logos/mercedes-benz.png";
export { default as logoRoyce } from "./logos/rolls-royce.png";
export { default as logoTesla } from "./logos/tesla.png";
export { default as logoVolvo } from "./logos/volvo.png";
